CREATE TABLE DEPARTAMENTO(
	CLAVE_DPTO NUMBER(1) NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	PRESUPUESTO NUMBER(5) NOT NULL,
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(CLAVE_DPTO)
);

CREATE TABLE EMPLEADOS(
	CLAVE_EMPLEADO VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDOS VARCHAR(30) NOT NULL,
	CLAVE_DPTO NUMBER(1) NOT NULL,
	CONSTRAINT EMPLEADOS PRIMARY KEY(CLAVE_EMPLEADO),
    CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY(CLAVE_DPTO) REFERENCES DEPARTAMENTO(CLAVE_DPTO)
);

INSERT INTO DEPARTAMENTO(CLAVE_DPTO, NOMBRE, PRESUPUESTO) VALUES(1, 'Personal', 80000);
INSERT INTO DEPARTAMENTO(CLAVE_DPTO, NOMBRE, PRESUPUESTO) VALUES(2, 'Almacén', 70000);
INSERT INTO DEPARTAMENTO(CLAVE_DPTO, NOMBRE, PRESUPUESTO) VALUES(3, 'Contabilidad', 60000);
INSERT INTO DEPARTAMENTO(CLAVE_DPTO, NOMBRE, PRESUPUESTO) VALUES(4, 'Manufactura', 50000);
INSERT INTO DEPARTAMENTO(CLAVE_DPTO, NOMBRE, PRESUPUESTO) VALUES(5, 'Empaque', 30000);

INSERT INTO EMPLEADOS(CLAVE_EMPLEADO, NOMBRE, APELLIDOS, CLAVE_DPTO) VALUES('EMP01', 'Armando', 'López', 2);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO, NOMBRE, APELLIDOS, CLAVE_DPTO) VALUES('EMP02', 'Tatiana', 'Vargas', 1);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO, NOMBRE, APELLIDOS, CLAVE_DPTO) VALUES('EMP03', 'Laura', 'García', 3);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO, NOMBRE, APELLIDOS, CLAVE_DPTO) VALUES('EMP04', 'Juan', 'Pérez', 4);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO, NOMBRE, APELLIDOS, CLAVE_DPTO) VALUES('EMP05', 'Iván', 'López', 4);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO, NOMBRE, APELLIDOS, CLAVE_DPTO) VALUES('EMP06', 'Margarita', 'Hernández', 1);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO, NOMBRE, APELLIDOS, CLAVE_DPTO) VALUES('EMP07', 'Jesús', 'Pérez', 3);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO, NOMBRE, APELLIDOS, CLAVE_DPTO) VALUES('EMP08', 'Toño', 'Flores', 2);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO, NOMBRE, APELLIDOS, CLAVE_DPTO) VALUES('EMP09', 'Juan', 'López', 4);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO, NOMBRE, APELLIDOS, CLAVE_DPTO) VALUES('EMP10', 'José', 'Hernández', 5);

SELECT NOMBRE, APELLIDOS FROM EMPLEADOS;

SELECT DISTINCT APELLIDOS FROM EMPLEADOS; 

SELECT * FROM EMPLEADOS WHERE APELLIDOS='López';

SELECT EMPLEADOS.NOMBRE, APELLIDOS, DEPARTAMENTO.NOMBRE FROM EMPLEADOS, DEPARTAMENTO WHERE EMPLEADOS.CLAVE_DPTO=DEPARTAMENTO.CLAVE_DPTO AND EMPLEADOS.NOMBRE LIKE '%a';

SELECT * FROM EMPLEADOS WHERE APELLIDOS IN('López', 'Pérez');

SELECT NOMBRE, CLAVE_EMPLEADO FROM EMPLEADOS WHERE CLAVE_DPTO=4;

SELECT NOMBRE, APELLIDOS FROM EMPLEADOS WHERE APELLIDOS LIKE 'H%';

SELECT * FROM DEPARTAMENTO WHERE PRESUPUESTO BETWEEN 50000 AND 70000;

SELECT CLAVE_EMPLEADO, EMPLEADOS.NOMBRE, APELLIDOS FROM EMPLEADOS, DEPARTAMENTO WHERE EMPLEADOS.CLAVE_DPTO=DEPARTAMENTO.CLAVE_DPTO AND LOWER (DEPARTAMENTO.NOMBRE)='contabilidad';

SELECT EMPLEADOS.NOMBRE, APELLIDOS, DEPARTAMENTO.NOMBRE FROM EMPLEADOS, DEPARTAMENTO WHERE EMPLEADOS.CLAVE_DPTO=DEPARTAMENTO.CLAVE_DPTO;

SELECT EMPLEADOS.CLAVE_DPTO, PRESUPUESTO, COUNT(*), PRESUPUESTO/COUNT(*) FROM EMPLEADOS, DEPARTAMENTO WHERE EMPLEADOS.CLAVE_DPTO=DEPARTAMENTO.CLAVE_DPTO GROUP BY EMPLEADOS.CLAVE_DPTO, PRESUPUESTO;

SELECT COUNT(*) FROM EMPLEADOS, DEPARTAMENTO WHERE EMPLEADOS.CLAVE_DPTO=DEPARTAMENTO.CLAVE_DPTO AND EMPLEADOS.NOMBRE LIKE 'J%' AND DEPARTAMENTO.NOMBRE='Manufactura';
