SELECT NOMBRE FROM CICLOFORM WHERE TIPO='GRADO SUPERIOR';

SELECT NOMBRE, AP1, AP2, DIRECCION FROM DATOSPERSONALES WHERE TIPO='PROFESOR';

SELECT NOMBRE FROM ASIGNATURA WHERE NUMHORAS BETWEEN 150 AND 250;

SELECT NOMBRE, CUENTA FROM DATOSPERSONALES, PROFESOR WHERE DATOSPERSONALES.DNI=PROFESOR.DNI_PROFESOR;

SELECT DNI FROM DATOSPERSONALES, MATRICULA WHERE DATOSPERSONALES.DNI=MATRICULA.DNI_ALUMNO AND MATRICULA.CODASIG=3;

SELECT DNI FROM DATOSPERSONALES, IDIOMASPROF WHERE DATOSPERSONALES.DNI=IDIOMASPROF.DNI_PROFESOR AND CODIDIOMA=20;

SELECT ASIGNATURA.NOMBRE FROM ASIGNATURA WHERE DNI_PROFESOR LIKE '89621477%';

SELECT DATOSPERSONALES.DNI FROM DATOSPERSONALES WHERE DATOSPERSONALES.NOMBRE IN('ANDREA', 'LUIS');
