<<<<<<< HEAD
ALTER TABLE DATOSPERSONALES ADD CONSTRAINT CK_TIPO CHECK(TIPO IN('N', 'D'));

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT CK_NUMPROF CHECK(NUMPROF BETWEEN 1 AND 30);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT UK_DESCRIPCION UNIQUE(DESCRIPCION);

ALTER TABLE DOCTORANDO ADD CONSTRAINT CK_FECHACOMIENZO CHECK(FECHACOMIENZO BETWEEN TO_DATE('01/01/2000', 'DD/MM/YYYY') AND SYSDATE);

ALTER TABLE DOCTOR ADD CONSTRAINT CK_TITULO CHECK(LENGTH(TITULO) > 9),
ALTER TABLE DOCTOR ADD CONSTRAINT UK_TITULO UNIQUE(TITULO),
ALTER TABLE DOCTOR ADD CONSTRAINT CK_CALIFICACION CHECK(CALIFICACION BETWEEN 0 AND 10);

ALTER TABLE CURSO ADD CONSTRAINT CK_DURACION CHECK(DURACION BETWEEN 10 AND 500);
=======
ALTER TABLE DATOSPERSONALES ADD CONSTRAINT CK_TIPO CHECK(TIPO IN('N', 'D'));

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT CK_NUMPROF CHECK(NUMPROF BETWEEN 1 AND 30);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT UK_DESCRIPCION UNIQUE(DESCRIPCION);

ALTER TABLE DOCTORANDO ADD CONSTRAINT CK_FECHACOMIENZO CHECK(FECHACOMIENZO BETWEEN TO_DATE('01/01/2000', 'DD/MM/YYYY') AND SYSDATE);

ALTER TABLE DOCTOR ADD CONSTRAINT CK_TITULO CHECK(LENGTH(TITULO) > 9),
ALTER TABLE DOCTOR ADD CONSTRAINT UK_TITULO UNIQUE(TITULO),
ALTER TABLE DOCTOR ADD CONSTRAINT CK_CALIFICACION CHECK(CALIFICACION BETWEEN 0 AND 10);

ALTER TABLE CURSO ADD CONSTRAINT CK_DURACION CHECK(DURACION BETWEEN 10 AND 500);
>>>>>>> d49ad1381e4bcc71f7374672f13527cefff5a8de
