ALTER TABLE DIRECTOR ADD CONSTRAINT UK_DIRECTOR UNIQUE(TELEFONO);
ALTER TABLE DIRECTOR ADD CONSTRAINT UK_DIRECTOR UNIQUE(EMAIL);
ALTER TABLE VENDEDOR ADD CONSTRAINT UK_VENDEDOR UNIQUE(TELEFONO);
ALTER TABLE VENDEDOR ADD CONSTRAINT UK_VENDEDOR UNIQUE(EMAIL);
ALTER TABLE CLIENTE ADD CONSTRAINT UK_CLIENTE UNIQUE(TELEFONO);
ALTER TABLE CLIENTE ADD CONSTRAINT UK_CLIENTE UNIQUE(EMAIL);

ALTER TABLE DIRECTOR ADD CONSTRAINT CK_DIRECTOR CHECK(TELEFONO = 9);
ALTER TABLE VENDEDOR ADD CONSTRAINT CK_VENDEDOR CHECK(TELEFONO = 9);
ALTER TABLE CLIENTE ADD CONSTRAINT CK_CLIENTE CHECK(TELEFONO = 9);

ALTER TABLE VENTA ADD CONSTRAINT CK_DNI CHECK(DNI_VENDEDOR <> DNI_CLIENTE);

ALTER TABLE PRODUCTO ADD CONSTRAINT UK_DESCRIPCION UNIQUE(DESCRIPCION);
ALTER TABLE PRODUCTO MODIFY CODFAMILIA NUMBER(4) REFERENCES FAMILIA(CODFAMILIA) ON DELETE SET NULL;
ALTER TABLE PRODUCTO MODIFY CODGENERO NUMBER(4) REFERENCES GENERO(CODGENERO) ON DELETE SET NULL;

ALTER TABLE LINEAVENTA MODIFY NUMLINEA NUMBER(2) CHECK(NUMLINEA BETWEEN 1 AND 99);
