CREATE TABLE TIPO_DP(
    CODTIPO NUMBER(4) NOT NULL,
	DESCRIPCION VARCHAR(40) NOT NULL,
    CONSTRAINT PK_TIPO_DP PRIMARY KEY(CODTIPO)
);

ALTER TABLE DATOSPERSONALES ADD CONSTRAINT FK_TIPO_DP FORE
IGN KEY(TIPO) REFERENCES TIPO_DP(CODTIPO);
ALTER TABLE DATOSPERSONALES MODIFY TELEFONO NOT NULL;
ALTER TABLE DATOSPERSONALES MODIFY CORREO NOT NULL;

ALTER TABLE DIRECTOR ADD ANIOS NUMBER(2) NOT NULL;

ALTER TABLE COMERCIAL DROP COLUMN COMISION;
ALTER TABLE ADD COMISION NUMBER(3) NOT NULL;

CREATE TABLE TURNO(
    CODTURNO NUMBER(4) NOT NULL,
	DESCRIPCION VARCHAR(40) NOT NULL,
    CONSTRAINT PK_TURNO PRIMARY KEY(CODTURNO)
);

ALTER TABLE VENDEDOR ADD CONSTRAINT FK_TURNO FOREIGN KEY(CODTURNO) REFERENCES TURNO(CODTURNO);

CREATE TABLE TEMATICA(
    CODTEM NUMBER(4) NOT NULL,
	DESCRIPCION VARCHAR(40) NOT NULL,
    CONSTRAINT PK_TEMATICA PRIMARY KEY(CODTEM)
);

ALTER TABLE LIBRO RENAME TEMATICA TO CODTEM;
ALTER TABLE LIBRO ADD CONSTRAINT FK_TEMATICA FOREIGN KEY(CODTEM) REFERENCES TEMATICA(CODTEM);
ALTER TABLE LIBRO RENAME PRECIO TO PRECIOACTURAL;
 