CREATE TABLE FABRICANTE(
    CODFAB NUMBER(4) NOT NULL,
    FABRICANTE VARCHAR(42) NOT NULL,
    CONSTRAINT PK_FABRICANTE PRIMARY KEY(CODFAB)
);

CREATE TABLE MARCA(
    CODMARCA NUMBER(4) NOT NULL,
    MARCA VARCHAR(255) NOT NULL,
    CONSTRAINT PK_MARCA PRIMARY KEY(CODMARCA)
);

CREATE TABLE VEHICULO(
    CODVEH NUMBER(4) NOT NULL,
    MODELO VARCHAR(42) NOT NULL,
    TIPO VARCHAR(24) NOT NULL,
    COLOR VARCHAR(90) NOT NULL,
    CODFAB NUMBER(4) NOT NULL,
    CODMARCA NUMBER(4) NOT NULL,
    CONSTRAINT PK_VEHICULO PRIMARY KEY(CODVEH),
    CONSTRAINT FK_FABRICANTE FOREIGN KEY(CODFAB) REFERENCES FABRICANTE(CODFAB),
    CONSTRAINT FK_MARCA FOREIGN KEY(CODMARCA) REFERENCES MARCA(CODMARCA)
);

CREATE TABLE CLIENTE(
    DNI_CLIENTE VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    AP1 VARCHAR(35) NOT NULL,
    AP2 VARCHAR(35) NULL,
    DOMICILIO VARCHAR(20) NOT NULL,
    NUMTARJETA VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(DNI_CLIENTE)
);

CREATE TABLE EMPLEADO(
    DNI_EMPLEADO VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    AP1 VARCHAR(35) NOT NULL,
    AP2 VARCHAR(35) NULL,
    DOMICILIO VARCHAR(20) NOT NULL,
    NUMCUENTA VARCHAR(20) NOT NULL,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY(DNI_EMPLEADO)
);

CREATE TABLE OFICINA(
    CODOFICINA NUMBER(4) NOT NULL,
    DOMICILIO VARCHAR(20) NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    CONSTRAINT PK_OFICINA PRIMARY KEY(CODOFICINA)
);

CREATE TABLE ALQUILER(
    CODALQUILER NUMBER(4) NOT NULL,
    FECHA DATE NOT NULL;
    NUMDIAS NUMBER(3) NOT NULL,
    KMACTUAL NUMBER(6) NOT NULL,
    KMENTREGA NUMBER(6) NOT NULL,
    DNI_CLIENTE VARCHAR(9) NOT NULL,
    DNI_EMPLEADO VARCHAR(9) NOT NULL,
    CODVEH NUMBER(4) NOT NULL,
    CODOFICINA NUMBER(4) NOT NULL,
    CONSTRAINT PK_ALQUILER PRIMARY KEY(CODALQUILER),
    CONSTRAINT FK_VEHICULO FOREIGN KEY(CODVEH) REFERENCES VEHICULO(CODVEH),
    CONSTRAINT FK_CLIENTE FOREIGN KEY(DNI_CLIENTE) REFERENCES CLIENTE(DNI_CLIENTE),
    CONSTRAINT FK_OFICINA FOREIGN KEY(CODOFICINA) REFERENCES OFICINA(CODOFICINA),
    CONSTRAINT FK_EMPLEADO FOREIGN KEY(DNI_EMPLEADO) REFERENCES EMPLEADO(DNI_EMPLEADO)
);

CREATE TABLE CURSO(
    CODCURSO NUMBER(4) NOT NULL,
    DESCRIPCION VARCHAR(40) NOT NULL,
    NUMHORAS NUMBER(3) NOT NULL,
    FECHA DATE NOT NULL;
    DNI_EMPLEADO VARCHAR(9) NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY(CODCURSO),
    CONSTRAINT FK_EMPLEADO FOREIGN KEY(DNI_EMPLEADO) REFERENCES EMPLEADO(DNI_EMPLEADO),
);
