CREATE TABLE OFICINA(
	CODOFICINA NUMBER(4) NOT NULL,
	DIRECCION VARCHAR(20) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	DNICOM VARCHAR(9) NOT NULL,
	DNIDIR VARCHAR(9) NOT NULL,
	CONSTRAINT PK_OFICINA PRIMARY KEY(CODOFICINA),
	CONSTRAINT FK_DIRECTOR FOREIGN KEY(DNIDIR) REFERENCES DIRECTOR(DNIDIR) ON DELETE CASCADE,
	CONSTRAINT CK_OFICINA CHECK(LENGTH(TELEFONO) =9)
);

CREATE TABLE COMERCIAL(
	DNICOM VARCHAR(9) NOT NULL,
	COMISION NUMBER(100) NOT NULL,
	CODOFICINA NUMBER(4) NOT NULL,
	CONSTRAINT PK_COMERCIAL PRIMARY KEY(DNICOM),
	CONSTRAINT FK_DATOSPERSONALES FOREIGN KEY(DNICOM) REFERENCES DATOSPERSONALES(DNI) ON DELETE CASCADE,
	CONSTRAINT CK_COMISION CHECK(COMISION >0 AND COMISION <100)
);

ALTER TABLE OFICINA ADD CONSTRAINT FK_COMERCIAL FOREIGN KEY(DNICOM) REFERENCES COMERCIAL(DNICOM) ON DELETE CASCADE;

ALTER TABLE COMERCIAL ADD CONSTRAINT FK_OFICINA FOREIGN KEY(CODOFICINA) REFERENCES OFICINA(CODOFICINA) ON DELETE CASCADE;

CREATE TABLE VENDEDOR(
	DNIVEN VARCHAR(9) NOT NULL,
	TURNO VARCHAR(6) NOT NULL,
	CODOFICINA NUMBER(4) NOT NULL,
	CONSTRAINT PK_VENDEDOR PRIMARY KEY(DNIVEN),
	CONSTRAINT FK_DATOSPERSONALES FOREIGN KEY(DNIVEN) REFERENCES DATOSPERSONALES(DNI) ON DELETE CASCADE,
	CONSTRAINT FK_OFICINA FOREIGN KEY(CODOFICINA) REFERENCES OFICINA(CODOFICINA) ON DELETE CASCADE,
	CONSTRAINT CK_TURNO CHECK(TURNO IN('MANIANA','TARDE','NOCHE'))
);