SELECT 
    NOMBRE
FROM 
    DATOSPERSONALES, PROFESOR, IDIOMA, IDIOMASPROF
WHERE 
    TIPO='PROFESOR' 
AND 
    DESCRIPCION='Español' 
AND 
    DATOSPERSONALES.DNI=PROFESOR.DNI_PROFESOR 
AND 
    PROFESOR.DNI_PROFESOR=IDIOMASPROF.DNI_PROFESOR 
AND 
    IDIOMASPROF.CODIDIOMA=IDIOMA.CODIDIOMA;

SELECT 
    ASIGNATURA.NOMBRE
FROM 
    CICLOFORM, ASIGNATURA
WHERE
    CICLOFORM.NOMBRE='DAM'
AND
    CICLOFORM.CODCICLO=ASIGNATURA.CODCICLO;

SELECT
    PROFESOR.CUENTA, DATOSPERSONALES.NOMBRE
FROM
    PROFESOR, DATOSPERSONALES
WHERE
    PROFESOR.DNI_PROFESOR=DATOSPERSONALES.DNI;

SELECT
    DATOSPERSONALES.*
FROM
    DATOSPERSONALES
WHERE
    DATOSPERSONALES.TIPO='ALUMNO';

SELECT
    DATOSPERSONALES.*
FROM
    DATOSPERSONALES
WHERE
    DATOSPERSONALES.TIPO='PROFESOR';

SELECT
    ALUMNO.EMAIL, DATOSPERSONALES.NOMBRE
FROM
    ALUMNO, DATOSPERSONALES
WHERE
    ALUMNO.DNI_ALUMNO=DATOSPERSONALES.DNI;

SELECT
    ALUMNO.EMAIL, DATOSPERSONALES.NOMBRE
FROM
    ALUMNO, DATOSPERSONALES, ASIGNATURA, MATRICULA
WHERE
    ASIGNATURA.NOMBRE='Empresa'
AND
    ALUMNO.DNI_ALUMNO=DATOSPERSONALES.DNI
AND 
    DATOSPERSONALES.DNI=MATRICULA.DNI_ALUMNO
AND
    MATRICULA.CODASIG=ASIGNATURA.CODASIG;

SELECT
    DATOSPERSONALES.NOMBRE, CICLOFORM.NOMBRE
FROM
    DATOSPERSONALES, CICLOFORM, ASIGNATURA, MATRICULA
WHERE
    DATOSPERSONALES.DNI=MATRICULA.DNI_ALUMNO
AND
    MATRICULA.CODASIG=ASIGNATURA.CODASIG
AND
    ASIGNATURA.CODCICLO=CICLOFORM.CODCICLO;

SELECT
    ASIGNATURA.NOMBRE, DATOSPERSONALES.NOMBRE
FROM
    ASIGNATURA, DATOSPERSONALES, MATRICULA
WHERE
    DATOSPERSONALES.NOMBRE='PEDRO'
AND
    ASIGNATURA.CODASIG=MATRICULA.CODASIG
AND
    MATRICULA.DNI_ALUMNO=DATOSPERSONALES.DNI;

SELECT
    CICLOFORM.NOMBRE
FROM
    CICLOFORM
WHERE
    CICLOFORM.TIPO='GRADO SUPERIOR';

SELECT
    CICLOFORM.NOMBRE, ASIGNATURA.NOMBRE
FROM
    CICLOFORM, ASIGNATURA
WHERE
    CICLOFORM.CODCICLO=ASIGNATURA.CODCICLO;

SELECT
    ASIGNATURA.NOMBRE
FROM
    ASIGNATURA
WHERE
    ASIGNATURA.NUMHORAS<'200';

SELECT
     DATOSPERSONALES.*
FROM
    DATOSPERSONALES
WHERE
    DATOSPERSONALES.NOMBRE='ANDREA';

UPDATE
    DATOSPERSONALES
SET
    DATOSPERSONALES.AP2=NULL
WHERE
    DATOSPERSONALES.NOMBRE='ANDREA';

SELECT
     *
FROM
    MATRICULA, ASIGNATURA
WHERE
    MATRICULA.CODASIG=ASIGNATURA.CODASIG
AND
    ASIGNATURA.NOMBRE='Programación';

DELETE
    MATRICULA
WHERE  
    MATRICULA.CODASIG=5;

SELECT
     ASIGNATURA.*
FROM
    MATRICULA, ASIGNATURA
WHERE
    MATRICULA.CODASIG=ASIGNATURA.CODASIG
AND
    ASIGNATURA.NOMBRE='Empresa';

DELETE
    MATRICULA
WHERE
    MATRICULA.CODASIG=1;

DELETE
    ASIGNATURA
WHERE
    ASIGNATURA.CODASIG=1;

SELECT
    *
FROM
    ASIGNATURA
WHERE
    ASIGNATURA.NOMBRE='Bases de datos';

UPDATE
    ASIGNATURA
SET
    ASIGNATURA.NOMBRE='BBDD'
WHERE
    ASIGNATURA.NOMBRE='Bases de datos';

INSERT INTO CICLOFORM(CODCICLO, NOMBRE, TIPO) VALUES(6365, 'ELEC', 'GRADO MEDIO');
INSERT INTO ASIGNATURA(CODASIG, NOMBRE, NUMHORAS, DNI_PROFESOR, CODCICLO) VALUES(1, 'Circuitos Baja Potencia', 100, '89621477A', 6365);

SELECT
    DATOSPERSONALES.NOMBRE, ASIGNATURA.NOMBRE
FROM
    MATRICULA, DATOSPERSONALES, ASIGNATURA
WHERE
    DATOSPERSONALES.DNI=MATRICULA.DNI_ALUMNO
AND
    MATRICULA.CODASIG=ASIGNATURA.CODASIG
AND
    DATOSPERSONALES.NOMBRE='PEDRO';

UPDATE
    MATRICULA
SET
    MATRICULA.CODASIG='3'
WHERE
    MATRICULA.CODASIG='2'
AND
    MATRICULA.DNI_ALUMNO='11526987G';

INSERT INTO IDIOMA(CODIDIOMA, DESCRIPCION) VALUES(50, 'Aleman');
INSERT INTO IDIOMASPROF(CODIDIOMA, DNI_PROFESOR) VALUES(50, '44103779F');
